services:
  - type: web
    name: francisai-security-system
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
